services:
  goboxd:
    build:
      context: .
      target: runtime
    image: goboxd:dev
    container_name: goboxd
    ports:
      - "8080:8080"
    privileged: true

  tools:
    build:
      context: .
      target: builder
    image: goboxd-tools:dev
    volumes:
      - .:/src
    working_dir: /src
    profiles: ["tools"]
    entrypoint: []
